# -*- coding: utf-8 -*-
"""test-unet

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qGuYCWo4xlHNPuzW7Uu1EcQPFMeONPwO
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount("drive")
# %cd "drive/My Drive/Satellite Imagery code"

!pip install import-ipynb
import import_ipynb
import utils
import unet
import torch
from torch.utils.data import DataLoader
from glob import glob as glob

model = unet.UNet()
utils.testModel(model, "saves/nobalance_noaug_lr1e-4_ternausloss0.5", "media/nobalance_noaug_lr1e-4_ternausloss0.5", video = False, figsize = 15)

model_path = "saves/nobalance_noaug_lr1e-4_ternausloss0.5"
saves = glob(f"{model_path}/epoch_*")
print(saves)
model.load_state_dict(torch.load(saves[0]))
model.eval()
dataset = utils.SatelliteDataset(root_dir = "data/dstl/testset", train = False, transform = None)
dataloader = iter(DataLoader(dataset, batch_size=5))
batch = next(dataloader)

model(batch).permute(0, 2, 3, 1).detach().numpy()

